name: "integration-test"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.14.x, 1.13.x]
    name: Test with Go version ${{ matrix.go-version }}
    steps:
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout
        uses: actions/checkout@v2
      - run: go test ./...
      - run: go run ./integration_test
        env:
          SECRET_KEY: xnd_development_chBDpzjQZEI8nncBLrWtwau5r7rgiuunCJ4JCqsd68rXemDd74BnRpdO0bIZAMK

  test-premod:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.12.x, 1.11.x]
    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: off
    name: Test with Go version ${{ matrix.go-version }}
    steps:
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ./src/github.com/${{ github.repository }}
      - name: deps installation
        run: |
          go get -u github.com/go-playground/validator
          go get -u github.com/joho/godotenv
          go get -u github.com/stretchr/testify
      - run: go test ./src/github.com/${{ github.repository }}/...
      - run: go run ./src/github.com/${{ github.repository }}/integration_test
        env:
          SECRET_KEY: xnd_development_n9wBjjLUDhHxiaA90owLxSnaUZxGxE1f264kNV7S3HjjPCmgOou1gJrznW4TFB
